### ISSUE TITLE
Подбирать адреса треков из URL

### ISSUE THREAD

**Issue by slazav** [wladich/EasyMapper#1]
Хотелось бы иметь возможность смотреть на трек, не только введя его адрес в соответствующее поле, но и запихав его в URL. В идеале - чтобы после ввода треков в поле они (в том или ином виде) появлялись и в URL-e, и можно было скопировать получившуюся ссылку...

**Comment by wladich** [comment]
Добавил в todo

**Comment by slazav** [comment]
Спасибо! Теперь есть еще следующее пожелание на эту тему: если у трека есть url - передавать не сами данные, а этот урл. Иначе для длинных треков получается уж очень длинная ссылка.

Вообще, было бы забавно так кодировать и передавать все состояние вьюера: загруженные по url треки, нарисованные треки и т.п.

**Comment by wladich** [comment]
Привет!
On 07/10/2016 08:35 PM, Vladislav Zavjalov wrote:

> Спасибо! Теперь есть еще следующее пожелание на эту тему: если у трека
> есть url - передавать не сами данные, а этот урл. Иначе для длинных
> треков получается уж очень длинная ссылка.
> Мысль хорошая, если трек не редактировали, то да, можно по url-у.
> Правда url может протухнуть... И надо дать понять, что вот эта вот 
> ссылка будем жить вечно, а эта как повезет...
> 
> Вообще, было бы забавно так кодировать и передавать все состояние
> вьюера: загруженные по url треки, нарисованные треки и т.п.

Это уже есть: справа вверху контрола треков многоточие -- там можно 
скопировать всё или только видимые.

**Comment by slazav** [comment]
Да, действительно, сложный интерфейс получается. Можно сделать две панельки: "показ внешних треков", где все передается по url и "редактор треков", куда можно загружать треки из url, из файла, рисовать, редактировать. И состояние редактора передавать с полными треками. Но это, все равно, довольно корявое решение.
