### ISSUE TITLE
про окошко с координатами

### ISSUE THREAD

**Issue by slazav** [wladich/EasyMapper#2]
Увидел, что слева появилось окошко с координатами. Мне кажется полезным, если бы можно было с помощью него совершать следующие действия:
- ткнуть мышкой в карту, скопировать из окошка полученные координаты
- ввести в окошко координаты и получить отметку на карте (хотя это требует введения нового объекта - точки на карте)
- уметь вводить координаты в разных форматах (по крайней мере dd.dddd, dd.mm.mm и dd.mm.ss)

**Comment by wladich** [comment]
Точно окошко и именно справа? Должна быть кнопка слева, при клике
разворачивается в окошко... Хотя состояния свёрнуто/развёрнуто сохраняется
между перезагрузками страницы. Дай скриншот, если не так и заодно ошобки из
консоли, если есть
1. Подумаю
2. Когда-нибудь будет поиск, это уйдёт туда. Или в загрузку точек из поля
ввода.
3. Уже -- правый клик -- будет меню

2016-07-10 23:51 GMT+03:00 Vladislav Zavjalov notifications@github.com:

**Comment by slazav** [comment]
Ну да, я именно эту кнопку и имел в виду. Право и лево перепутал.

**Comment by wladich** [comment]
1. Сделал, через меню на контроле координат
